version: "3.8"
   
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=neuralworks
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  python:
    image: python:3.10.10
    build:
      context: .
      dockerfile: python.dockerfile
    container_name: python
    depends_on:
      - db
    ports: 
      - 8000:8000
    volumes:
      - ./scripts:/home/scripts
      - ./csv:/home/csv
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 6556:6556
  #   environment:
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  #     - PGADMIN_DEFAULT_EMAIL=test@neuralworks.cl
  #     - PGADMIN_LISTEN_PORT=6556